name: API Document

on:
  push:
    branches:
      - main
  pull_request:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
        override: true
    - name: Build docs
      run: |
        cargo rustdoc
        echo "/ /awr 301" > target/doc/_redirects
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: target/doc

  deploy:
    name: Develop Deploy
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/heads/')"
    needs: [ build ]
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup netlify cli
      run: npm install -g netlify-cli
    - uses: actions/download-artifact@v3
      with:
        name: docs
        path: target/doc
    - name: Deploy to netlify
      run: netlify deploy --dir=target/doc --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
  release-deploy:
    name: Production Deploy
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ build ]
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup netlify cli
      run: npm install -g netlify-cli
    - uses: actions/download-artifact@v3
      with:
        name: docs
        path: target/doc
    - name: Deploy to netlify
      run: netlify deploy --dir=target/doc --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
     
